---
  env:
    node: true
    es2020: true

  plugins:
    - 'jest'

  extends:
    - 'airbnb-base'
    - 'plugin:jest/recommended'

  parserOptions:
    ecmaVersion: 11
    sourceType: module

  rules:
    import/extensions: 0
    no-console: 0
