name: hexlet-check

on:
  - push
  - pull_request
  

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: git clone 
        uses: actions/checkout@v2 frontend-project-lvl2 repository
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: make install
      - name: Run linter
        uses: make lint
